### ISSUE TITLE
要望：Options で class の Prefix を指定したい

### ISSUE THREAD

**Issue by okamoai** [kkoudev/postcss-webfont#3]
適用するプロジェクトによっては CSS 設計方針でクラス名をコントロールしたいこともあるので、
出力されるクラス名をオプションである程度コントロールできると嬉しいです。
従来の class フォーマットをデフォルトとすると、例えば以下のような内容です。
```js
postcss([webfont({
  classNamePrefix: 'iconfont', 
  classNameBeforePrefix: 'iconfont-before', 
  classNameAfterPrefix: 'iconfont-after', 
})])
```
`classNameBeforePrefix` `classNameAfterPrefix` は false 指定で
class の出力をスキップできるとなお良いです。

**Comment by kkoudev** [comment]
@okamoai  ご要望ありがとうございます！
近日中に対応しますのでお待ちください。

**Comment by okamoai** [comment]
ご対応ありがとうございます！
自分の方でも修正を PR してみました。#7
