### ISSUE TITLE
要望：font-src の cachebuster がビルドの度に差分がでないようにしたい

### ISSUE THREAD

**Issue by okamoai** [kkoudev/postcss-webfont#4]
ビルドをすると以下のようにキャッシュ回避のための cachebuster が追加されますが、
```
src: url('../font/icon.woff2?1686377cc55')
```
getTime() を使っているため、ビルドの度に cachebuster が変化して、
差分が計上されます。 ビルドファイルを Git に含める環境だと
Web フォントに修正がなくても Git で差分が出てしまうので
cachebuster  の値をコントロールする方法として以下2点ができると助かります。

- 現状、 `fixedHash` オプションで cachebuster に固定値を入れられますが、固定値か getTime() の2択なので、cachebuster そのものを無効にする手段（例えば false 指定など）があると嬉しいいです
- cachebuster の生成を src の SVG ファイルを基に CRC で生成するというのはどうでしょうか。src ファイルが変更されない限りは cachebuster  の値が変更されず、CSSの差分が発生しなくなります

**Comment by kkoudev** [comment]
@okamoai  ご要望ありがとうございます！
近日中に対応しますのでお待ちください。
