### ISSUE TITLE
要望：svgicons2svgfont の prependUnicode オプションを適用したい

### ISSUE THREAD

**Issue by okamoai** [kkoudev/postcss-webfont#5]
svgicons2svgfont  に渡せるオプションに `prependUnicode` を追加いただけけませんでしょうか。
https://github.com/nfroidure/svgicons2svgfont#new-svgicons2svgfontstreamoptions
Webフォントに追加がある際に CSS 側の unicode 値が都度変化しなくなります。

**Comment by kkoudev** [comment]
@okamoai  ご要望ありがとうございます！
近日中に対応しますのでお待ちください。
